main: me.thecamzone.Engine.Main
name: MCRPG
version: 0.0.1
description: Provides gameplay mechanics for MCRPG.
api-version: 1.19
author: TheCamZone
commands:
  mcrpg:
    description: Main command for administrators
    aliases: []
    permission: mcrpg.admin
    permission-message: "Unknown command. Type \"/help\" for help."
    usage: /<command>
  setwarp:
    description: Sets warp at location where run.
    aliases: []
    permission: mcrpg.setwarp
    permission-message: "Unknown command. Type \"/help\" for help."
    usage: /<command> <location>
  delwarp:
    description: Removes a warp location
    aliases: []
    permission: mcrpg.delwarp
    permission-message: "Unknown command. Type \"/help\" for help."
    usage: /<command> <location>
  warp:
    description: Sets warp at location where run.
    aliases: [warps, w]
    permission: mcrpg.warp
    permission-message: "Unknown command. Type \"/help\" for help."
    usage: /<command> [warp]